---
- name: tst RAAP
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - juniper.space

  tasks:
    - name : test
      uri:
        url: "https://{{ rna_uri }}/a/aiopsremediation/prod/solvecongestion?api_key=57c5c9c9-86e7-463d-80d2-7e8c76fab5e6"
        method: POST
        follow_redirects: all
        return_content: yes
        status_code: 200
        force_basic_auth: yes
        validate_certs: false
        headers:
          Content-Type: application/json
          Accept: application/json
        body_format: json
        body: { "delay": "{{ delay_to_set }}", "vm": "{{ wanem_vm }}" }
      register: result
    
    - name: debug
      debug:
        msg: "{{ result }}"
