---
- name: tst Kube
  hosts: all
  gather_facts: no

  tasks:
    - name: Login to OpenShift cluster
      shell: |
        oc login --server=https://"{{ocp_fqdn}}" -u "{{ocp_user}}" -p "{{ocp_password}}" --insecure-skip-tls-verify=true
      args:
        executable: /bin/bash

    - name: qui suis je
      shell: |
        whoami
      register: whoami      

    - name: debug whoami
      debug:
        msg: "{{ whoami }}"

    - name: ou suis je
      shell: |
        echo $HOME
      register: ousuisje      

    - name: debug ousuisje
      debug:
        msg: "{{ ousuisje }}"        